# Generated by Django 3.2 on 2021-05-30 17:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DelayedMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='mail_app/mails')),
                ('send_on', models.DateTimeField(default=datetime.datetime(2021, 5, 30, 17, 19, 40, 273251, tzinfo=utc))),
                ('recipients_list', models.ManyToManyField(related_name='mail_list', to='send_mail.MailRecipient')),
            ],
        ),
    ]
