# Generated by Django 3.2 on 2021-05-30 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delayedmail',
            name='recipients_list',
        ),
        migrations.RemoveField(
            model_name='delayedmail',
            name='send_on',
        ),
        migrations.RemoveField(
            model_name='delayedmail',
            name='template',
        ),
        migrations.AddField(
            model_name='mailrecipient',
            name='send_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 17, 50, 10, 119, tzinfo=utc)),
        ),
    ]
