# Generated by Django 3.2 on 2021-05-30 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0002_auto_20210530_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailrecipient',
            name='send_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 18, 14, 50, 55086, tzinfo=utc)),
        ),
    ]
