# Generated by Django 3.2 on 2021-05-30 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0003_alter_mailrecipient_send_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailrecipient',
            name='send_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 19, 26, 4, 604114, tzinfo=utc)),
        ),
    ]
