# Generated by Django 3.2 on 2021-04-24 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter description of the product', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular furniture', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('m', 'Many'), ('s', 'Single'), ('n', 'Not available'), ('r', 'Reserved')], default='m', help_text='Furniture availability', max_length=1)),
                ('Furniture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.furniture')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='furniture',
            name='type',
            field=models.ManyToManyField(help_text='Select a type of this product', to='catalog.Type'),
        ),
    ]
