# Generated by Django 3.2 on 2021-05-29 08:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Описание продукта', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('published', models.BooleanField(default=False, help_text='Опубликовано')),
                ('image', models.CharField(help_text='Изображение продукта', max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=1000.2, max_digits=6)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
            ],
            options={
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product type', max_length=200)),
                ('testfield', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular furniture', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('a', 'В наличии'), ('n', 'Куплен'), ('r', 'Зарезервирован')], default='a', help_text='Furniture availability', max_length=1)),
                ('delivery_day', models.DateField(default=datetime.date(2021, 6, 8), help_text='Delivery day')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('furniture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.furniture')),
            ],
            options={
                'ordering': ['status'],
                'permissions': (('worker', 'Can manage catalog items (WORKER)'),),
            },
        ),
        migrations.AddField(
            model_name='furniture',
            name='type',
            field=models.ManyToManyField(help_text='Выберите тип продукта', to='catalog.Type'),
        ),
    ]
