# Generated by Django 3.2 on 2021-04-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitureinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('n', 'Not available'), ('r', 'Reserved')], default='m', help_text='Furniture availability', max_length=1),
        ),
    ]
