# Generated by Django 3.2 on 2021-05-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='testfield',
        ),
    ]
