# Generated by Django 3.2 on 2021-05-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_furnitureinstance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
