# Generated by Django 3.2 on 2021-05-30 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_type_testfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitureinstance',
            name='delivery_day',
            field=models.DateField(default=datetime.date(2021, 6, 9), help_text='Delivery day'),
        ),
    ]
