# Generated by Django 3.2 on 2021-05-30 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_furnitureinstance_delivery_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitureinstance',
            name='delivery_day',
            field=models.DateField(default=datetime.date(2021, 6, 10), help_text='Delivery day'),
        ),
    ]
